server:
  context-path: /sell
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.2.126/we_chat_order?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1/we_chat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true