server:
  context-path: /sell
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.2.126/we_chat_order?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://127.0.0.1/we_chat_order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

#微信配置参数
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret:
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12